<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.jenkins-ci.plugins</groupId>
        <artifactId>plugin</artifactId>
        <version>6.2236.v12dd4c483242</version>
        <relativePath />
    </parent>

    <groupId>io.jenkins.plugins</groupId>
    <artifactId>tdoms</artifactId>
    <version>${changelist}</version>
    <packaging>hpi</packaging>

    <name>TD/OMS Integration Plugin</name>
    <inceptionYear>2026</inceptionYear>
    <description>Jenkins plugin for TD/OMS on IBM i to push changed sources to IFS and trigger deployments.</description>
    <url>https://github.com/jenkinsci/${project.artifactId}-plugin</url>

    <scm>
        <connection>scm:git:https://github.com/${gitHubRepo}.git</connection>
        <developerConnection>scm:git:https://github.com/${gitHubRepo}.git</developerConnection>
        <url>https://github.com/${gitHubRepo}</url>
    </scm>

    <issueManagement>
        <system>GitHub</system>
        <url>https://github.com/RemainSoftware/omsjenkins/issues</url>
    </issueManagement>

    <properties>
        <changelist>999999-SNAPSHOT</changelist>
        <gitHubRepo>RemainSoftware/omsjenkins</gitHubRepo>
        <jenkins.baseline>2.541</jenkins.baseline>
        <jenkins.version>${jenkins.baseline}.3</jenkins.version>
        <banObsoleteDependencyOverrides.skip>false</banObsoleteDependencyOverrides.skip>
        <ban-junit4-imports.skip>false</ban-junit4-imports.skip>
        <ban-deprecated-stapler.skip>false</ban-deprecated-stapler.skip>
        <ban-commons-lang-2.skip>false</ban-commons-lang-2.skip>
    </properties>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
        </license>
    </licenses>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.jenkins.tools.bom</groupId>
                <artifactId>bom-2.541.x</artifactId>
                <version>7002.v028a_3607ddc8</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.jenkins-ci.plugins.workflow</groupId>
            <artifactId>workflow-step-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>credentials</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>git-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.jenkins.plugins</groupId>
            <artifactId>ibmi-steps</artifactId>
            <version>136.vf3eb_2466c306</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/public/</url>
        </repository>
        <repository>
            <id>jenkins-releases</id>
            <url>https://repo.jenkins-ci.org/releases/</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/public/</url>
        </pluginRepository>
        <pluginRepository>
            <id>jenkins-releases</id>
            <url>https://repo.jenkins-ci.org/releases/</url>
        </pluginRepository>
    </pluginRepositories>

</project>
